services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db/Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    container_name: app
    depends_on:
      - db
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
  ui:
    container_name: ui
    image: nginx
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - 80:80
