services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db/Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
  app:
    depends_on:
      - db
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
  ui:
    image: nginx
    restart: on-failure
    volumes:
      - ./frontend/:/usr/share/nginx/html:ro
    ports:
      - 80:80

