version: '3.4'

services:
  p1-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
  p1mehrab:
    image: p1mehrab
    depends_on:
      - p1-db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
