services:
  p1-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db/Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
  app:
    depends_on:
      - p1-db
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
